version: "3"

services:
  app:
    image: alindragut/idp:latest
    depends_on:
      - db
    ports:
      - '5000:5000'
    networks:
      - backend
    deploy:
      replicas: 2
      resources:
        limits:
          cpus: "0.2"
          memory: 50M
      restart_policy:
        condition: on-failure

  db:
    image: alindragut/idp:db
    restart: always
    environment:
      MYSQL_ROOT_PASSWORD: root
    ports:
      - '32000:3306'
    volumes:
      - db:/var/lib/mysql
    networks:
      - backend
    deploy:
      placement:
        constraints: [node.role == manager]

networks:
  backend:

volumes:
  db:
