FROM python:2.7
COPY professor.py /usr/src/app/
COPY requirements.txt /usr/src/app/
COPY templates_professor/ /usr/src/app/templates/
RUN pip install -r /usr/src/app/requirements.txt
CMD [ "python", "./usr/src/app/professor.py" ]
